### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/ocaml#393]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/ocaml/issues/384)
- [ ] [Add key features](https://github.com/exercism/ocaml/issues/385)
- [ ] [Add tags](https://github.com/exercism/ocaml/issues/386)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/ocaml/issues/387)
- [ ] [Update status of track](https://github.com/exercism/ocaml/issues/391)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/ocaml/issues/392)
- [ ] [Pass linting checks](https://github.com/exercism/ocaml/issues/388)
- [ ] [Build Test Runner](https://github.com/exercism/ocaml/issues/389)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/ocaml/issues/390) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
